import { Inter } from 'next/font/google';
import type { Metadata } from 'next';

export const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Chaos App',
  description: 'Generated by chaos',
};
